present_store/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import IndexTemplateView
import products

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexTemplateView.as_view(), name="index"),
    path("products/", include('products.urls', namespace='products')),
]

products/urls.py
from django.urls import path, include
from .views import CatalogTemplateView, ProductsCatalogListView

app_name = 'products'
urlpatterns = [
    path('catalog/', CatalogTemplateView.as_view(), name="catalog"),
    path('catalog/products_catalog/', ProductsCatalogListView.as_view(), name="products_catalog"),
    path('catalog/products_catalog/filter_products/', ProductsCatalogListView.as_view(), name="filter_products"),
]

products/models.py
from django.db import models


# Create your models here.

class Products(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    subcategory = models.ForeignKey('Subcategory', on_delete=models.SET_NULL, null=True, blank=True)

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)

    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    is_edible = models.BooleanField(default=False)  # True - съедобный, False - несъедобный
    purpose = models.CharField(max_length=100)  # Например: "для кухни", "для бани", "в гости", "косметические наборы"
    price = models.DecimalField(max_digits=10, decimal_places=2)
    visits_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    def __str__(self):
        return self.title

class Subcategory(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

products/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView

from django.http import JsonResponse
from django.views import View
import json
from .models import Products, Category, Subcategory


class IndexTemplateView(TemplateView):
    template_name = "products/index.html"


class CatalogTemplateView(TemplateView):
    template_name = "products/catalog.html"


# class ProductsCatalogListView(ListView):
#     model = Products
#     context_object_name = 'products'
#     template_name = "products/products_catalog.html"
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super(ProductsCatalogListView, self).get_context_data(object_list=None, **kwargs)
#         context['products'] = Products.objects.all()
#
#         return context
#
#     def get_queryset(self):
#         return Products.objects.all()
#
#     def your_django_view(self):
#         if self.request.method == 'POST':
#             data = json.loads(self.request.body)
#             # Выполните сортировку товаров на основе данных из 'data'
#             # Верните ответ клиенту (например, список отсортированных товаров)
#             response_data = {
#                 'message': 'Данные успешно обработаны и отсортированы',
#                 # Добавьте нужные данные для клиента
#             }
#             print(response_data)
#             return JsonResponse(response_data)
#         else:
#             # Обработка GET-запроса или других случаев
#             # Верните HTML-шаблон или другой контент, который вам нужен
#             pass

class ProductsCatalogListView(ListView):
    model = Products
    context_object_name = 'products'
    template_name = "products/products_catalog.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsCatalogListView, self).get_context_data(object_list=None, **kwargs)
        context['products'] = Products.objects.all()

        return context

    def get_queryset(self):
        return Products.objects.all()

    def post(self, request, *args, **kwargs):
        # Получите данные о выбранных чекбоксах из запроса
        selected_checkboxes = request.POST.getlist('selected_checkboxes[]')

        # Осуществите фильтрацию товаров на основе выбранных чекбоксов (пример)
        # filtered_products = Products.objects.filter()
        #
        # # Сериализуйте отфильтрованные товары в формат JSON
        # data = [{'id': product.id, 'name': product.name} for product in filtered_products]
        if 'composition_checkbox_edible' in selected_checkboxes:
            filtered_products = Products.objects.filter(is_edible=True)
        else:
            filtered_products = Products.objects.all()
        data = [{'id': product.id, 'title': product.title, 'is_edible': product.is_edible, 'price': product.price} for product in filtered_products]
        print(data)

        return JsonResponse({'products': data})

products/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'products/css/style.css' %}">
    <title id="titleHead">{% block title %}{% endblock %}</title>
</head>
<body>

<div class="upheader">
<div class="container">
    <div class="upheader_inner">
        <img class="upheader_logo" src="{% static "products/icons/upheader/logo.svg" %}">
        <div class="upheader_slider">
            <button class="upheader_slider_previous"><img src="{% static 'products/icons/upheader/previous.svg' %}" alt="previous"></button>
            <div class="upheader_slider_inner">
                <div class="upheader_slider_line">

                    <div class="upheader_slider_line_item">

                        <div class="upheader_slider_line_item_circle">
                            <img src="{% static "products/icons/upheader/Quality.svg" %}" alt="" class="upheader_slider_line_item_circle_img">
                        </div>
                        <div class="upheader_slider_line_item_text">Гарантия качества</div>

                    </div>
                    <div class="upheader_slider_line_item">

                        <div class="upheader_slider_line_item_circle">
                            <img src="{% static "products/icons/upheader/Discount.svg" %}" alt="" class="upheader_slider_line_circle_item_img">
                        </div>
                        <div class="upheader_slider_line_item_text">Система скидок</div>

                    </div>
                    <div class="upheader_slider_line_item">

                        <div class="upheader_slider_line_item_circle">
                            <img src="{% static "products/icons/upheader/b.svg" %}" alt="" class="upheader_slider_line_circle_item_img">
                        </div>
                        <div class="upheader_slider_line_item_text">Бесплатная открытка</div>

                    </div>
                    <div class="upheader_slider_line_item">

                        <div class="upheader_slider_line_item_circle">
                            <img src="{% static "products/icons/upheader/a.svg" %}" alt="" class="upheader_slider_line_circle_item_img">
                        </div>
                        <div class="upheader_slider_line_item_text">Анонимная доставка</div>

                    </div>

                </div>
            </div>
            <button class="upheader_slider_next"><img src="{% static 'products/icons/upheader/next.svg' %}" alt="next"></button>
        </div>
        <div class="upheader_contacts">
            <div class="upheader_contacts_line1">
                <img src="{% static "products/icons/upheader/telegram.svg" %}" alt="wh">
                <span class="upheader_span">+7 (985) 223-40-59</span>
            </div>
            <div class="upheader_contacts_line2">
                <img src="{% static "products/icons/upheader/whatsap.svg" %}" alt="tel">
                <span class="upheader_span">с 9:00 до 19:00 (Пн-Сб)</span>
            </div>
        </div>
        <div class="upheader_buttons">
            <a href="#" class="upheader_buttons_basket"><img src="{% static "products/icons/upheader/basket.svg" %}" alt="basket"></a>
            <a href="#" class="upheader_buttons_login"><img src="{% static "products/icons/upheader/login.svg" %}" alt="basket">Войти</a>
        </div>
    </div>
</div>
</div>
<div class="header">
<div class="container">
    <div class="header_inner">
        <div class="header_main">
            <img class="header_main_img" src="{% static "products/icons/header/hurt.svg" %}" alt="hurt">
            <a href="{% url "index" %}" style="text-decoration: none; color:#464646">Главная</a>
        </div>
        <a href="{% url "products:catalog" %}" class="header_button">Каталог подарков</a>
        <nav class="header_nav">
            <a class="header_nav_item" href="#">О нас</a>
            <a class="header_nav_item" href="#">Доставка</a>
            <a class="header_nav_item" href="#">Акции</a>
            <a class="header_nav_item" href="#">Скидки</a>
            <a class="header_nav_item" href="#">Контакты</a>
        </nav>

    </div>
</div>
</div>
{% block content %}{% endblock %}

<footer class="footer">
<div class="container">
<div class="footer_inner">
    <div class="footer_block_left">
    <img src="{% static "products/icons/footer/logo-footer.png" %}" alt="logo" class="footer_logo">
    <span>Политика конфиденциальности</span>
    <span>Copyright © 2023, комплименты</span>
</div>
    <div class="footer_block_middle">
    <div class="footer_block_middle_left">
        <span>Каталог подарков</span>
        <span>О нас</span>
        <span>Контакты</span>
    </div>
    <div class="footer_block_middle_right">
        <span>Доставка</span>
        <span>Акции</span>
        <span>Скидки</span>
    </div>
</div>
    <div class="footer_block_right">
    <span>+7 (985) 223-40-59</span>
    <span>info@complimente.ru</span>
    <span>с 9:00 до 19:00 (Пн-Сб)</span>
    <div class="footer_block_right_icons">
        <img src="{% static "products/icons/footer/telegram.svg" %}" alt="" class="footer_block_right_icons-telegram">
        <img src="{% static "products/icons/footer/whatsapp (1).svg" %}" alt="" class="footer_block_right_icons-whatsapp">
    </div>
</div>
</div>
</div>
</footer>

<script src="{% static 'products/js/script.js' %}"></script>
</body>
</html>

products/templates/products/catalog.html
{% extends "../base.html" %}
{% load static %}

{% block content %}
<div class="catalog">
<div class="container">
    <h1 class="catalog_title">Каталог подарков</h1>
    <div class="infoblock_inner">
        <a href="#" class="infoblock_item">
            <div class="infoblock_item_text">К праздникам</div>
            <img src="{% static 'products/img/Rectangle 10.png' %}" alt="img" class="infoblock_item_img">
        </a>
        <a href="#" class="infoblock_item">
            <div class="infoblock_item_text infoblock_item_text-right">Для нее</div>
            <img src="{% static 'products/img/Rectangle 13.png' %}" alt="img" class="infoblock_item_img">
        </a>
        <a href="#" class="infoblock_item">
            <div class="infoblock_item_text infoblock_item_text-bot">Для него</div>
            <img src="{% static 'products/img/Rectangle 14.png' %}" alt="img" class="infoblock_item_img">
        </a>
        <a href="#" class="infoblock_item">
            <div class="infoblock_item_text">Корпоративные</div>
            <img src="{% static 'products/img/Rectangle 15.png' %}" alt="img" class="infoblock_item_img">
        </a>
    </div>

    <div class="catalog_child">
        <div class="catalog_child_inner">
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/1.jpeg" %}" alt="1" class="catalog_child_item_img">
                <a href="" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">Новый год</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/2.jpeg" %}" alt="2" class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">8 марта</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/3.jpeg" %}" alt="3" class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">23 февраля</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/4.jpeg" %}" alt="4" class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">день учителя</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/5.jpeg" %}" alt="5" class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">1 сентября</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/6.jpeg" %}" alt="6" class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">день рождения</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/7.jpeg" %}" alt="7" class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">Ураза-байрам</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/8.jpeg" %}" alt="8" class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">день матери</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/9.jpeg" %}" alt="9" class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">рождение ребенка</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/10.jpeg" %}" alt="10" class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">подарки детям</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/11.jpeg" %}" alt="11" class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">для бани</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/12.jpeg" %}" alt="12" class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">для кухни</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/13.jpeg" %}" alt="13 class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">косметические наборы</div>
                </a>
            </div>
            <div class="catalog_child_item">
                <img src="{% static "products/img/catalog/14.jpeg" %}" alt="14" class="catalog_child_item_img">
                <a href="#" class="catalog_child_item_inner">
                    <div class="catalog_child_item_text">в гости</div>
                </a>
            </div>
            <div class="catalog_child_item-xl">
                <a href="{% url 'products:products_catalog' %}" class="catalog_child_item-xl_text">Все подарки</a>
            </div>
        </div>
    </div>
</div>
</div>
<div class="present_block">
    <img src="{% static "products/img/Rectangle 95.png" %}" alt="img" class="first_present_img">
    <div class="present_block_info">
        <div class="present_block_info_title">получите скидку 5%</div>
        <div class="present_block_info_text">Подпишитесь на наши новости и акции и получите постоянную скидку 5%</div>
    </div>
    <a href="#" class="present_block_btn">Подписаться</a>
    <img src="{% static "products/img/Rectangle 93.png" %}" alt="img" class="second_present_img">
</div>

{% endblock %}

products/templates/products/products_catalog.html
{% extends '../base.html' %}
{% load static %}
{% block title %}products_catalog{% endblock %}

{% block content %}
<div class="pr_catalog">
<div class="container">
<div class="pr_catalog_inner">
    <div class="pr_catalog_filter">
        <h2 class="pr_catalog_filter_title">Фильтр</h2>
        <div class="pr_catalog_filter_inner">
            <a href="#" class="pr_catalog_filter_clean">Очистить фильтр</a>

            <div class="pr_catalog_filter_item">
                <div class="pr_catalog_filter_item_title">Категория</div>
                <div class="pr_catalog_filter_category">
                    <a href="#" class="pr_catalog_filter_category_item">Все подарки</a>
                    <a href="#" class="pr_catalog_filter_category_item">Для него</a>
                    <a href="#" class="pr_catalog_filter_category_item">Для нее</a>
                    <a href="#" class="pr_catalog_filter_category_item">Для детей</a>

                    <div class="select">
                        <div class="select_header">
                            <span class="select_current"><a href="#" class="pr_catalog_filter_category_item">К праздникам</a></span>
                            <img src="{% static 'products/icons/filter/Otkrivashka.svg' %}" class="select_icon">
                        </div>

                        <div class="select_body">
                            <a href="#" class="select_item">Новый год</a>
                            <a href="#" class="select_item">8 марта</a>
                            <a href="#" class="select_item">23 февраля</a>
                            <a href="#" class="select_item">День рождения</a>
                            <a href="#" class="select_item">День матери</a>
                            <a href="#" class="select_item">Рождение ребенка</a>
                        </div>
                    </div>

                </div>
            </div>
            <form action="" id="filter-form" method="post">
                {% csrf_token %}
                <div class="pr_catalog_filter_item">
                    <div class="pr_catalog_filter_item_title">состав подарков</div>
                    <div class="pr_catalog_filter_composition">
                        <div class="pr_catalog_filter_composition_inner">
                            <label class="pr_catalog_filter_checkbox_item">
                                <input type="checkbox" class="pr_catalog_filter_checkbox" id="composition_checkbox_edible">
                                <span class="pr_catalog_filter_custom_checkbox"></span>
                                <label for="composition_checkbox_edible" class="pr_catalog_filter_label">съедобные</label>
                            </label>
                            <label class="pr_catalog_filter_checkbox_item">
                                <input type="checkbox" class="pr_catalog_filter_checkbox" id="composition_checkbox_inedible">
                                <span class="pr_catalog_filter_custom_checkbox"></span>
                                <label for="composition_checkbox_inedible" class="pr_catalog_filter_label">несъедобные</label>
                            </label>
                        </div>
                    </div>
                </div>

                <div class="pr_catalog_filter_item">
                    <div class="pr_catalog_filter_item_title">Назначение</div>
                    <div class="pr_catalog_filter_composition">
                        <div class="pr_catalog_filter_composition_inner">
                            <label class="pr_catalog_filter_checkbox_item">
                                <input type="checkbox" class="pr_catalog_filter_checkbox" id="appointment_checkbox_kitchen">
                                <span class="pr_catalog_filter_custom_checkbox"></span>
                                <label for="appointment_checkbox_kitchen" class="pr_catalog_filter_label">Для кухни</label>
                            </label>
                            <label class="pr_catalog_filter_checkbox_item">
                                <input type="checkbox" class="pr_catalog_filter_checkbox" id="appointment_checkbox_bedroom">
                                <span class="pr_catalog_filter_custom_checkbox"></span>
                                <label for="appointment_checkbox_bedroom" class="pr_catalog_filter_label">Для бани</label>
                            </label>
                            <label class="pr_catalog_filter_checkbox_item">
                                <input type="checkbox" class="pr_catalog_filter_checkbox" id="appointment_checkbox_guests">
                                <span class="pr_catalog_filter_custom_checkbox"></span>
                                <label for="appointment_checkbox_guests" class="pr_catalog_filter_label">В гости</label>
                            </label>
                            <label class="pr_catalog_filter_checkbox_item">
                                <input type="checkbox" class="pr_catalog_filter_checkbox" id="appointment_checkbox_cosmetics">
                                <span class="pr_catalog_filter_custom_checkbox"></span>
                                <label for="appointment_checkbox_cosmetics" class="pr_catalog_filter_label">Косметические наборы</label>
                            </label>
                        </div>
                    </div>
                </div>

                <div class="pr_catalog_filter_item">
                    <div class="pr_catalog_filter_item_title">упаковка</div>
                    <div class="pr_catalog_filter_composition">
                        <div class="pr_catalog_filter_composition_inner">
                            <label class="pr_catalog_filter_checkbox_item">
                                <input type="checkbox" class="pr_catalog_filter_checkbox" id="package_checkbox_busket">
                                <span class="pr_catalog_filter_custom_checkbox"></span>
                                <label for="package_checkbox_busket" class="pr_catalog_filter_label">корзина</label>
                            </label>
                            <label class="pr_catalog_filter_checkbox_item">
                                <input type="checkbox" class="pr_catalog_filter_checkbox" id="package_checkbox_box">
                                <span class="pr_catalog_filter_custom_checkbox"></span>
                                <label for="package_checkbox_box" class="pr_catalog_filter_label">коробка</label>
                            </label>
                            <label class="pr_catalog_filter_checkbox_item">
                                <input type="checkbox" class="pr_catalog_filter_checkbox" id="package_checkbox_paket">
                                <span class="pr_catalog_filter_custom_checkbox"></span>
                                <label for="package_checkbox_paket" class="pr_catalog_filter_label">пакет</label>
                            </label>
                            <label class="pr_catalog_filter_checkbox_item">
                                <input type="checkbox" class="pr_catalog_filter_checkbox" id="package_checkbox_case">
                                <span class="pr_catalog_filter_custom_checkbox"></span>
                                <label for="package_checkbox_case" class="pr_catalog_filter_label">ящик</label>
                            </label>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
    <div class="pr_catalog_products">
        <h2 class="pr_catalog_products_title">Каталог подарков</h2>
        <div class="pr_catalog_products_sort">
{#            <div class="pr_catalog_products_sort_inner">#}
{#                <select name="pr_catalog_products_sort" id="">#}
{#                    <option>По убыванию цены</option>#}
{#                    <option>По возрастанию цены</option>#}
{#                    <option>По популярности</option>#}
{#                </select>#}
{#            </div>#}
            <div class="sort_select">
                <div class="sort_select_title">Сортировать:</div>
                <div class="sort_select_inner">
                        <div class="sort_select_header">
                        <span class="sort_select_current">По умолчанию</span>
                        <img src="{% static 'products/icons/filter/Otkrivashka.svg' %}" class="sort_select_icon">
                    </div>

                    <div class="sort_select_body">
                        <div class="sort_select_item">По убыванию цены</div>
                        <div class="sort_select_item">По возрастанию цены</div>
                        <div class="sort_select_item">По умолчанию</div>
                    </div>
                </div>
            </div>

        </div>
        <div class="products_inner-for_catalog">
            <div class="products_line-for_catalog" id="products_line-for_catalog">
{#                {% for product in products %}#}
{#                    <div class="products_item products_item-for_catalog">#}
{#                        <img src="{% static "products/img/products_slider/Rectangle 21.png" %}" alt="1" class="products_item_img">#}
{#                        <div class="products_item_info">#}
{#                            <div class="products_item_info_art">арт. 1234556</div>#}
{#                            <div class="products_item_info_title">{{ product.title }}</div>#}
{#                            <div class="products_item_info_price">{{ product.price }} ₽</div>#}
{#                            <div class="products_item_info_quantity">#}
{#                                <a href="#" class="products_item_info_quantity_add_btn"><img src="{% static "products/icons/products/+ (1).svg" %}" alt="1"></a>#}
{#                                <div class="products_item_info_quantity_number">1</div>#}
{#                                <a href="#" class="products_item_info_quantity_subtract_btn"><img src="{% static "products/icons/products/+.svg" %}" alt=""></a>#}
{#                            </div>#}
{#                            <a href="#" class="products_item_info_add_to_basket_btn">В корзину</a>#}
{#                        </div>#}
{#                    </div>#}
{#                {% endfor %}#}
{#                <div class="products_item products_item-for_catalog">#}
{#                    <img src="{% static "products/img/products_slider/Rectangle 21.png" %}" alt="1" class="products_item_img">#}
{#                    <div class="products_item_info">#}
{#                        <div class="products_item_info_art">арт. 1234556</div>#}
{#                        <div class="products_item_info_title">Набор 5 (8 марта)</div>#}
{#                        <div class="products_item_info_price">3 880 ₽</div>#}
{#                        <div class="products_item_info_quantity">#}
{#                            <a href="#" class="products_item_info_quantity_add_btn"><img src="{% static "products/icons/products/+ (1).svg" %}" alt="1"></a>#}
{#                            <div class="products_item_info_quantity_number">1</div>#}
{#                            <a href="#" class="products_item_info_quantity_subtract_btn"><img src="{% static "products/icons/products/+.svg" %}" alt=""></a>#}
{#                        </div>#}
{#                        <a href="#" class="products_item_info_add_to_basket_btn">В корзину</a>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="products_item products_item-for_catalog">#}
{#                    <img src="{% static "products/img/products_slider/Rectangle 21 (1).png" %}" alt="1" class="products_item_img">#}
{#                    <div class="products_item_info">#}
{#                        <div class="products_item_info_art">арт. 1234556</div>#}
{#                        <div class="products_item_info_title">Набор 4 (8 марта)</div>#}
{#                        <div class="products_item_info_price">3 880 ₽</div>#}
{#                        <div class="products_item_info_quantity">#}
{#                            <a href="#" class="products_item_info_quantity_add_btn"><img src="{% static "products/icons/products/+ (1).svg" %}" alt="1"></a>#}
{#                            <div class="products_item_info_quantity_number">1</div>#}
{#                            <a href="#" class="products_item_info_quantity_subtract_btn"><img src="{% static "products/icons/products/+.svg" %}" alt=""></a>#}
{#                        </div>#}
{#                        <a href="#" class="products_item_info_add_to_basket_btn">В корзину</a>#}
{#                    </div>#}
{#                </div>#}

            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}